# Generated by Django 4.0.3 on 2022-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(related_name='users', to='calcapp.user'),
        ),
    ]
